### ISSUE TITLE
Configure hardware -  .hwconf file not created 

### ISSUE THREAD

**Issue by SoniaZotz** [nrbrook/BGDemo#1]
**Configure hardware**
Cannot configure hardware  the .hwconf not found Simplicity Studio Version: SV4.1.11.5

Open the .hwconf file in your project, and make sure the 'Configurator' perspective is selected in the top toolbar.
Would you please help 

Thank You

**Comment by nrbrook** [comment]
Unfortunately shortly after I created this tutorial, SI Labs made significant changes to simplicity studio which broke the project and tutorial. I have not since had time to fix it, sorry. I may revisit it in the coming months. If you figure it out, feel free to submit a pull request. Or if you want further assistance, please reach out directly via my business, https://nrbtech.io

**Comment by SoniaZotz** [comment]
thank you ...and so it goes with SI Labs

**Comment by SoniaZotz** [comment]
https://www.silabs.com/community/wireless/bluetooth/forum.topic.html/hardware_configurato-z0Y1
so the problem is not solved

**Comment by nrbrook** [comment]
No, they removed the hardware configuration. So now it all has to be done by hand. 🤷‍♂️

**Comment by SoniaZotz** [comment]
![Fixed](https://user-images.githubusercontent.com/10633874/64738940-b6f69980-d4be-11e9-8dbd-bc3080fb7eda.jpg)
